/**
 * Dados Mock - Simulação de Backend
 * Entidades: users, students, teachers, courses, subjects, classes, attendance, calls, payments, documents
 */

import { database, KEYS } from './database';

// Usuários para login
export const mockUsers = [
  { id: '1', email: 'aluno@edusenac.com', password: '123456', type: 'student', studentId: '1' },
  { id: '2', email: 'professor@edusenac.com', password: '123456', type: 'teacher', teacherId: '1' },
];

// Alunos - simulando alunos de diferentes cursos SENAC MG
export const mockStudents = [
  {
    id: '1',
    name: 'João Silva',
    email: 'aluno@edusenac.com',
    enrollment: '2024001',
    cpf: '12345678901',
    courseId: '1',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
  },
  {
    id: '5',
    name: 'Lucas Mendes',
    email: 'lucas@edusenac.com',
    enrollment: '2024005',
    cpf: '56789012345',
    courseId: '1',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
  },
  {
    id: '6',
    name: 'Fernanda Costa',
    email: 'fernanda.a@edusenac.com',
    enrollment: '2024006',
    cpf: '67890123456',
    courseId: '1',
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
  },
  {
    id: '7',
    name: 'Rafael Souza',
    email: 'rafael@edusenac.com',
    enrollment: '2024007',
    cpf: '78901234567',
    courseId: '1',
    photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400',
  },
  {
    id: '8',
    name: 'Juliana Lima',
    email: 'juliana@edusenac.com',
    enrollment: '2024008',
    cpf: '89012345678',
    courseId: '1',
    photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400',
  },
  {
    id: '9',
    name: 'Bruno Almeida',
    email: 'bruno@edusenac.com',
    enrollment: '2024009',
    cpf: '90123456789',
    courseId: '1',
    photo: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400',
  },
  {
    id: '10',
    name: 'Camila Rodrigues',
    email: 'camila@edusenac.com',
    enrollment: '2024010',
    cpf: '01234567890',
    courseId: '1',
    photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
  },
  {
    id: '2',
    name: 'Mariana Oliveira',
    email: 'mariana@edusenac.com',
    enrollment: '2024002',
    cpf: '23456789012',
    courseId: '2',
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
  },
  {
    id: '3',
    name: 'Pedro Henrique',
    email: 'pedro@edusenac.com',
    enrollment: '2024003',
    cpf: '34567890123',
    courseId: '4',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
  },
  {
    id: '4',
    name: 'Ana Carolina',
    email: 'ana.c@edusenac.com',
    enrollment: '2024004',
    cpf: '45678901234',
    courseId: '3',
    photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
  },
];

// Professores
export const mockTeachers = [
  {
    id: '1',
    name: 'Maria Santos',
    email: 'professor@edusenac.com',
    employeeId: 'EMP001',
    cpf: '98765432100',
    department: 'Técnico em Desenvolvimento de Sistemas',
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600',
    rating: 4.8,
    curriculoResumo:
      'Especialista em desenvolvimento mobile com React Native. Mais de 10 anos de experiência em ensino e projetos corporativos.',
    formacao: [
      'Mestrado em Engenharia de Software - UFMG (2015)',
      'Graduação em Ciência da Computação - PUC Minas (2010)',
      'Especialização em UX/UI - Senac (2018)',
    ],
    especialidade: 'Desenvolvimento Mobile, React Native, Expo, UX em Apps',
    tempoCarreira: '12 anos',
    materias: ['Programação Mobile', 'Banco de Dados', 'Desenvolvimento Web', 'Gestão de Pessoas', 'Redes de Computadores', 'Fundamentos de Enfermagem', 'Gestão de Estoques'],
    tese: 'Otimização de Performance em Aplicativos React Native para Dispositivos de Baixo Custo',
    pesquisa: 'Pesquisa em acessibilidade mobile e inclusão digital. Publicações em SBC e IEEE.',
  },
  {
    id: '2',
    name: 'Carlos Oliveira',
    email: 'carlos@edusenac.com',
    employeeId: 'EMP002',
    department: 'Técnico em Desenvolvimento de Sistemas',
    photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=600',
    rating: 4.5,
    curriculoResumo:
      'Doutor em Ciência da Computação. Especialista em modelagem de dados e bancos relacionais.',
    formacao: [
      'Doutorado em Ciência da Computação - USP (2018)',
      'Mestrado em Banco de Dados - Unicamp (2012)',
      'Graduação em Sistemas de Informação - UFMG (2008)',
    ],
    especialidade: 'Banco de Dados, Modelagem, SQL, NoSQL, Big Data',
    tempoCarreira: '16 anos',
    materias: ['Banco de Dados', 'Modelagem de Dados', 'Data Science'],
    tese: 'Técnicas de Otimização de Consultas em Bancos de Dados Distribuídos',
    pesquisa: 'Pesquisador em sistemas distribuídos. Artigos em VLDB e SIGMOD.',
  },
  {
    id: '3',
    name: 'Ana Ferreira',
    email: 'ana@edusenac.com',
    employeeId: 'EMP003',
    department: 'Técnico em Desenvolvimento de Sistemas',
    photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=600',
    rating: 4.9,
    curriculoResumo:
      'Desenvolvedora full-stack e instrutora. Experiência em React, Vue e Node.js.',
    formacao: [
      'Mestrado em Tecnologia da Informação - FUMEC (2019)',
      'Graduação em Engenharia de Software - UFJF (2014)',
      'Bootcamp Full-Stack - Rocketseat (2020)',
    ],
    especialidade: 'Frontend, React, Vue, Node.js, Acessibilidade Web',
    tempoCarreira: '9 anos',
    materias: ['Desenvolvimento Web', 'Frontend Avançado', 'Acessibilidade'],
    tese: 'Frameworks JavaScript e Impacto na Acessibilidade de Aplicações Web',
    pesquisa: 'Estudos sobre WCAG e inclusão digital. Colaboradora em projetos open source.',
  },
  {
    id: '4',
    name: 'Roberto Mendes',
    email: 'roberto@edusenac.com',
    employeeId: 'EMP004',
    department: 'Técnico em Administração',
    photo: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=600',
    rating: 4.6,
    curriculoResumo: 'Especialista em gestão empresarial e planejamento estratégico. MBA em Administração.',
    formacao: ['MBA em Gestão Empresarial - FGV', 'Graduação em Administração - UFMG'],
    especialidade: 'Gestão de Pessoas, Marketing, Finanças',
    tempoCarreira: '14 anos',
    materias: ['Gestão de Pessoas', 'Contabilidade e Finanças', 'Marketing e Vendas'],
  },
  {
    id: '5',
    name: 'Fernanda Costa',
    email: 'fernanda@edusenac.com',
    employeeId: 'EMP005',
    department: 'Técnico em Enfermagem',
    photo: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=600',
    rating: 4.9,
    curriculoResumo: 'Enfermeira com especialização em urgência e emergência. Experiência em ensino técnico.',
    formacao: ['Especialização em Urgência e Emergência - UFMG', 'Graduação em Enfermagem - PUC Minas'],
    especialidade: 'Fundamentos de Enfermagem, Semiologia, Anatomia',
    tempoCarreira: '11 anos',
    materias: ['Fundamentos de Enfermagem', 'Anatomia e Fisiologia', 'Semiologia e Semiotécnica'],
  },
  {
    id: '6',
    name: 'Paulo Souza',
    email: 'paulo@edusenac.com',
    employeeId: 'EMP006',
    department: 'Técnico em Redes de Computadores',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600',
    rating: 4.7,
    curriculoResumo: 'Especialista em redes e infraestrutura. Certificações Cisco e CompTIA.',
    formacao: ['Especialização em Redes - CEFET', 'Graduação em Sistemas de Informação - UFMG'],
    especialidade: 'Redes, Segurança da Informação, Infraestrutura',
    tempoCarreira: '13 anos',
    materias: ['Redes de Computadores', 'Segurança da Informação', 'Infraestrutura de TI'],
  },
];

// Cursos - SENAC Minas Gerais (cursos técnicos oferecidos pela instituição)
export const mockCourses = [
  { id: '1', name: 'Técnico em Desenvolvimento de Sistemas', code: 'DS' },
  { id: '2', name: 'Técnico em Administração', code: 'ADM' },
  { id: '3', name: 'Técnico em Redes de Computadores', code: 'RED' },
  { id: '4', name: 'Técnico em Enfermagem', code: 'ENF' },
  { id: '5', name: 'Técnico em Logística', code: 'LOG' },
  { id: '6', name: 'Técnico em Estética', code: 'EST' },
  { id: '7', name: 'Técnico em Nutrição e Dietética', code: 'NUT' },
  { id: '8', name: 'Técnico em Recursos Humanos', code: 'RH' },
  { id: '9', name: 'Técnico em Segurança do Trabalho', code: 'SST' },
  { id: '10', name: 'Técnico em Agronegócio', code: 'AGR' },
  { id: '11', name: 'Técnico em Farmácia', code: 'FAR' },
];

// Disciplinas (carga horária em horas) - por curso SENAC MG
export const mockSubjects = [
  // Curso 1 - Técnico em Desenvolvimento de Sistemas
  { id: '1', name: 'Programação Mobile', code: 'PM', courseId: '1', workload: 80 },
  { id: '2', name: 'Banco de Dados', code: 'BD', courseId: '1', workload: 60 },
  { id: '3', name: 'Desenvolvimento Web', code: 'DW', courseId: '1', workload: 80 },
  { id: '4', name: 'Algoritmos e Programação', code: 'AP', courseId: '1', workload: 80 },
  { id: '5', name: 'Análise de Sistemas', code: 'AS', courseId: '1', workload: 60 },
  // Curso 2 - Técnico em Administração
  { id: '6', name: 'Gestão de Pessoas', code: 'GP', courseId: '2', workload: 60 },
  { id: '7', name: 'Contabilidade e Finanças', code: 'CF', courseId: '2', workload: 80 },
  { id: '8', name: 'Marketing e Vendas', code: 'MV', courseId: '2', workload: 60 },
  { id: '9', name: 'Logística Empresarial', code: 'LE', courseId: '2', workload: 60 },
  // Curso 3 - Técnico em Redes de Computadores
  { id: '10', name: 'Redes de Computadores', code: 'RC', courseId: '3', workload: 80 },
  { id: '11', name: 'Segurança da Informação', code: 'SI', courseId: '3', workload: 60 },
  { id: '12', name: 'Infraestrutura de TI', code: 'IT', courseId: '3', workload: 80 },
  // Curso 4 - Técnico em Enfermagem
  { id: '13', name: 'Fundamentos de Enfermagem', code: 'FE', courseId: '4', workload: 120 },
  { id: '14', name: 'Anatomia e Fisiologia', code: 'AF', courseId: '4', workload: 80 },
  { id: '15', name: 'Semiologia e Semiotécnica', code: 'SS', courseId: '4', workload: 80 },
  // Curso 5 - Técnico em Logística
  { id: '16', name: 'Gestão de Estoques', code: 'GE', courseId: '5', workload: 60 },
  { id: '17', name: 'Transporte e Distribuição', code: 'TD', courseId: '5', workload: 80 },
  { id: '18', name: 'Compras e Suprimentos', code: 'CS', courseId: '5', workload: 60 },
  // Curso 6 - Técnico em Estética
  { id: '19', name: 'Estética Facial', code: 'EF', courseId: '6', workload: 80 },
  { id: '20', name: 'Estética Corporal', code: 'EC', courseId: '6', workload: 80 },
  { id: '21', name: 'Cosmetologia', code: 'COS', courseId: '6', workload: 60 },
  // Curso 7 - Técnico em Nutrição e Dietética
  { id: '22', name: 'Nutrição Clínica', code: 'NC', courseId: '7', workload: 80 },
  { id: '23', name: 'Técnica Dietética', code: 'TD2', courseId: '7', workload: 80 },
  { id: '24', name: 'Higiene e Segurança Alimentar', code: 'HSA', courseId: '7', workload: 60 },
  // Curso 8 - Técnico em Recursos Humanos
  { id: '25', name: 'Recrutamento e Seleção', code: 'RS', courseId: '8', workload: 60 },
  { id: '26', name: 'Treinamento e Desenvolvimento', code: 'TED', courseId: '8', workload: 60 },
  { id: '27', name: 'Legislação Trabalhista', code: 'LT', courseId: '8', workload: 60 },
  // Curso 9 - Técnico em Segurança do Trabalho
  { id: '28', name: 'NRs e Normas de Segurança', code: 'NR', courseId: '9', workload: 80 },
  { id: '29', name: 'Ergonomia', code: 'ERG', courseId: '9', workload: 60 },
  { id: '30', name: 'Prevenção de Acidentes', code: 'PA', courseId: '9', workload: 60 },
  // Curso 10 - Técnico em Agronegócio
  { id: '31', name: 'Gestão Rural', code: 'GR', courseId: '10', workload: 60 },
  { id: '32', name: 'Agricultura e Pecuária', code: 'AP2', courseId: '10', workload: 80 },
  { id: '33', name: 'Comercialização Agrícola', code: 'CA', courseId: '10', workload: 60 },
  // Curso 11 - Técnico em Farmácia
  { id: '34', name: 'Farmácia Clínica', code: 'FC', courseId: '11', workload: 80 },
  { id: '35', name: 'Manipulação de Medicamentos', code: 'MM', courseId: '11', workload: 80 },
  { id: '36', name: 'Farmacologia', code: 'FAR', courseId: '11', workload: 60 },
];

// Turmas/Aulas (compatibilidade com API existente)
export const mockClasses = [
  {
    id: '1',
    subjectId: '1',
    teacherId: '1',
    schedule: '08:00 - 10:00',
    dayOfWeek: 1,
    room: 'Sala 101',
    semester: '2024.1',
    location: { latitude: -15.835214, longitude: -48.012034, radius: 500 },
  },
  {
    id: '2',
    subjectId: '2',
    teacherId: '1',
    schedule: '10:00 - 12:00',
    dayOfWeek: 2,
    room: 'Sala 102',
    semester: '2024.1',
    location: { latitude: -15.835214, longitude: -48.012034, radius: 500 },
  },
  {
    id: '3',
    subjectId: '3',
    teacherId: '1',
    schedule: '14:00 - 16:00',
    dayOfWeek: 3,
    room: 'Sala 103',
    semester: '2024.1',
    location: { latitude: -15.835214, longitude: -48.012034, radius: 500 },
  },
  {
    id: '10',
    subjectId: '1',
    teacherId: '1',
    schedule: '08:00 - 10:00',
    dayOfWeek: 3,
    room: 'Sala 101',
    semester: '2024.1',
    location: { latitude: -15.835214, longitude: -48.012034, radius: 500 },
  },
  {
    id: '11',
    subjectId: '2',
    teacherId: '1',
    schedule: '10:00 - 12:00',
    dayOfWeek: 3,
    room: 'Sala 102',
    semester: '2024.1',
    location: { latitude: -15.835214, longitude: -48.012034, radius: 500 },
  },
  {
    id: '4',
    subjectId: '2',
    teacherId: '1',
    schedule: '10:00 - 12:00',
    dayOfWeek: 1,
    room: 'Sala 102',
    semester: '2024.1',
    location: { latitude: -15.835214, longitude: -48.012034, radius: 500 },
  },
  {
    id: '5',
    subjectId: '3',
    teacherId: '1',
    schedule: '14:00 - 16:00',
    dayOfWeek: 1,
    room: 'Sala 103',
    semester: '2024.1',
    location: { latitude: -15.835214, longitude: -48.012034, radius: 500 },
  },
  {
    id: '6',
    subjectId: '1',
    teacherId: '1',
    schedule: '10:00 - 12:00',
    dayOfWeek: 4,
    room: 'Sala 101',
    semester: '2024.1',
    location: { latitude: -15.835214, longitude: -48.012034, radius: 500 },
  },
  {
    id: '7',
    subjectId: '3',
    teacherId: '1',
    schedule: '14:00 - 16:00',
    dayOfWeek: 4,
    room: 'Sala 103',
    semester: '2024.1',
    location: { latitude: -15.835214, longitude: -48.012034, radius: 500 },
  },
  {
    id: '8',
    subjectId: '1',
    teacherId: '1',
    schedule: '08:00 - 10:00',
    dayOfWeek: 5,
    room: 'Sala 101',
    semester: '2024.1',
    location: { latitude: -15.835214, longitude: -48.012034, radius: 500 },
  },
  {
    id: '9',
    subjectId: '2',
    teacherId: '1',
    schedule: '10:00 - 12:00',
    dayOfWeek: 5,
    room: 'Sala 102',
    semester: '2024.1',
    location: { latitude: -15.835214, longitude: -48.012034, radius: 500 },
  },
  {
    id: '12',
    subjectId: '1',
    teacherId: '1',
    schedule: '09:00 - 11:00',
    dayOfWeek: 6,
    room: 'Sala 101',
    semester: '2024.1',
    location: { latitude: -15.835214, longitude: -48.012034, radius: 500 },
  },
  {
    id: '13',
    subjectId: '3',
    teacherId: '1',
    schedule: '14:00 - 16:00',
    dayOfWeek: 0,
    room: 'Sala 103',
    semester: '2024.1',
    location: { latitude: -15.835214, longitude: -48.012034, radius: 500 },
  },
  // 2023.2
  { id: '20', subjectId: '1', teacherId: '1', schedule: '08:00-10:00', dayOfWeek: 1, room: 'Sala 101', semester: '2023.2', location: { latitude: -15.835214, longitude: -48.012034, radius: 500 } },
  { id: '21', subjectId: '2', teacherId: '2', schedule: '10:00-12:00', dayOfWeek: 2, room: 'Sala 102', semester: '2023.2', location: { latitude: -15.835214, longitude: -48.012034, radius: 500 } },
  { id: '22', subjectId: '3', teacherId: '3', schedule: '14:00-16:00', dayOfWeek: 3, room: 'Sala 103', semester: '2023.2', location: { latitude: -15.835214, longitude: -48.012034, radius: 500 } },
  // 2024.2
  { id: '30', subjectId: '1', teacherId: '1', schedule: '08:00-10:00', dayOfWeek: 1, room: 'Sala 101', semester: '2024.2', location: { latitude: -15.835214, longitude: -48.012034, radius: 500 } },
  { id: '31', subjectId: '2', teacherId: '2', schedule: '10:00-12:00', dayOfWeek: 2, room: 'Sala 102', semester: '2024.2', location: { latitude: -15.835214, longitude: -48.012034, radius: 500 } },
  { id: '32', subjectId: '3', teacherId: '3', schedule: '14:00-16:00', dayOfWeek: 3, room: 'Sala 103', semester: '2024.2', location: { latitude: -15.835214, longitude: -48.012034, radius: 500 } },
  // Turmas dos demais cursos SENAC MG - 2024.1 (atribuídas ao professor 1 para simulação)
  { id: '40', subjectId: '6', teacherId: '1', schedule: '08:00-10:00', dayOfWeek: 1, room: 'Sala 201', semester: '2024.1', location: { latitude: -15.835214, longitude: -48.012034, radius: 500 } },
  { id: '41', subjectId: '7', teacherId: '1', schedule: '10:00-12:00', dayOfWeek: 2, room: 'Sala 201', semester: '2024.1', location: { latitude: -15.835214, longitude: -48.012034, radius: 500 } },
  { id: '42', subjectId: '10', teacherId: '1', schedule: '14:00-16:00', dayOfWeek: 1, room: 'Lab. Redes 1', semester: '2024.1', location: { latitude: -15.835214, longitude: -48.012034, radius: 500 } },
  { id: '43', subjectId: '13', teacherId: '1', schedule: '08:00-12:00', dayOfWeek: 2, room: 'Lab. Enfermagem', semester: '2024.1', location: { latitude: -15.835214, longitude: -48.012034, radius: 500 } },
  { id: '44', subjectId: '16', teacherId: '1', schedule: '14:00-16:00', dayOfWeek: 3, room: 'Sala 202', semester: '2024.1', location: { latitude: -15.835214, longitude: -48.012034, radius: 500 } },
];

// Aulas - Organizado por dia com hora e professor responsável
// dayOfWeek: 0=domingo, 1=segunda, 2=terça, 3=quarta, 4=quinta, 5=sexta, 6=sábado
export const mockAulas = [
  {
    id: 'a1',
    classId: '1',
    dia: 'segunda',
    dayOfWeek: 1,
    hora: '08:00',
    horaFim: '10:00',
    disciplina: 'Programação Mobile',
    subjectId: '1',
    professor: 'Maria Santos',
    teacherId: '1',
    sala: 'Sala 101',
    semester: '2024.1',
    resumo: 'Introdução ao React Native e Expo. Estrutura de componentes, navegação e estilização.',
    conteudo: [
      'Introdução ao React Native e Expo',
      'Estrutura de componentes e JSX',
      'Navegação entre telas (Stack Navigator)',
      'Estilização e layout com StyleSheet',
      'Hooks: useState e useEffect',
      'Integração com APIs REST',
      'Persistência local com AsyncStorage',
      'Publicação na Play Store e App Store',
      'Configuração do ambiente de desenvolvimento',
      'Expo CLI e EAS Build',
      'Componentes nativos vs customizados',
      'Debug com React Native Debugger',
      'Performance e otimização de listas',
      'Gestos e animações com Reanimated',
      'Integração com câmera e sensores',
      'Push notifications e background tasks',
      'Testes unitários e E2E',
      'Acessibilidade em apps mobile',
    ],
  },
  {
    id: 'a1b',
    classId: '4',
    dia: 'segunda',
    dayOfWeek: 1,
    hora: '10:00',
    horaFim: '12:00',
    disciplina: 'Banco de Dados',
    subjectId: '2',
    professor: 'Maria Santos',
    teacherId: '1',
    sala: 'Sala 102',
    semester: '2024.1',
    resumo: 'Modelagem de dados e SQL. Normalização, consultas e integração com aplicações.',
    conteudo: [
      'Modelagem de dados e diagrama ER',
      'SQL: SELECT, INSERT, UPDATE, DELETE',
      'Normalização (1FN, 2FN, 3FN)',
      'Joins e subconsultas',
      'Índices e performance',
      'Transações e ACID',
      'Integração com aplicações (ORM)',
      'Boas práticas de modelagem',
      'Diagrama entidade-relacionamento',
      'Cardinalidade e relacionamentos',
      'Chaves primárias e estrangeiras',
      'Views materializadas',
      'Stored procedures e functions',
      'Triggers e eventos',
      'Backup incremental e full',
      'Plano de recuperação de desastres',
      'Monitoramento e tuning',
      'Segurança e criptografia de dados',
    ],
  },
  {
    id: 'a1c',
    classId: '5',
    dia: 'segunda',
    dayOfWeek: 1,
    hora: '14:00',
    horaFim: '16:00',
    disciplina: 'Desenvolvimento Web',
    subjectId: '3',
    professor: 'Maria Santos',
    teacherId: '1',
    sala: 'Sala 103',
    semester: '2024.1',
    resumo: 'HTML5, CSS3 e JavaScript. Componentes reutilizáveis e responsividade.',
    conteudo: [
      'HTML5 e semântica',
      'CSS3 e flexbox/grid',
      'JavaScript ES6+ (arrow functions, destructuring)',
      'Componentes reutilizáveis',
      'Responsividade e media queries',
      'Acessibilidade (a11y)',
      'Performance e otimização',
      'Ferramentas de desenvolvimento',
      'Tags semânticas: header, main, footer, nav',
      'Flexbox: flex-direction, justify, align',
      'Grid: template areas e auto-fit',
      'Variáveis CSS e custom properties',
      'Animações @keyframes',
      'Transições e transform',
      'Formulários HTML5 e validação',
      'APIs: Geolocation, Storage, Fetch',
      'Web Workers e performance',
      'PWA e service workers',
    ],
  },
  {
    id: 'a2',
    classId: '2',
    dia: 'terça',
    dayOfWeek: 2,
    hora: '14:00',
    horaFim: '16:00',
    disciplina: 'Banco de Dados',
    subjectId: '2',
    professor: 'Maria Santos',
    teacherId: '1',
    sala: 'Sala 102',
    semester: '2024.1',
    resumo: 'Modelagem de dados e SQL. Normalização, consultas e integração com aplicações.',
    conteudo: [
      'Revisão: modelagem ER',
      'Consultas avançadas (GROUP BY, HAVING)',
      'Views e stored procedures',
      'Triggers e constraints',
      'Backup e recuperação',
      'Segurança e permissões',
      'Otimização de queries',
      'Window functions: ROW_NUMBER, RANK',
      'CTEs (Common Table Expressions)',
      'Recursive queries',
      'Full-text search',
      'Particionamento de tabelas',
      'Replicação master-slave',
      'Connection pooling',
      'Query execution plans',
      'Índices compostos e covering',
    ],
  },
  {
    id: 'a3',
    classId: '3',
    dia: 'terça',
    dayOfWeek: 2,
    hora: '08:00',
    horaFim: '10:00',
    disciplina: 'Desenvolvimento Web',
    subjectId: '3',
    professor: 'Maria Santos',
    teacherId: '1',
    sala: 'Sala 103',
    semester: '2024.1',
    resumo: 'HTML5, CSS3 e JavaScript. Componentes reutilizáveis e responsividade.',
    conteudo: [
      'Estrutura semântica HTML5',
      'Flexbox e Grid Layout',
      'Variáveis CSS e temas',
      'Animações e transições',
      'Formulários e validação',
      'APIs do navegador',
      'BEM e metodologias CSS',
      'Pré-processadores (SASS/LESS)',
      'Mobile-first design',
      'Breakpoints e containers',
      'Imagens responsivas (srcset)',
      'Lazy loading e performance',
      'SEO e meta tags',
      'Structured data (JSON-LD)',
      'Cross-browser compatibility',
    ],
  },
  {
    id: 'a4a',
    classId: '10',
    dia: 'quarta',
    dayOfWeek: 3,
    hora: '08:00',
    horaFim: '10:00',
    disciplina: 'Programação Mobile',
    subjectId: '1',
    professor: 'Maria Santos',
    teacherId: '1',
    sala: 'Sala 101',
    semester: '2024.1',
    resumo: 'Introdução ao React Native e Expo. Estrutura de componentes, navegação e estilização.',
    conteudo: [
      'Configuração do ambiente Expo',
      'Componentes básicos (View, Text, Image)',
      'TouchableOpacity e gestos',
      'FlatList e ScrollView',
      'Navegação com React Navigation',
      'Temas e modo escuro',
      'Expo SDK e módulos nativos',
      'SafeAreaView e notch',
      'StatusBar e barra de navegação',
      'KeyboardAvoidingView',
      'Refs e imperativo handle',
      'Error boundaries',
      'Logging e crash reporting',
      'Over-the-air updates',
      'Build para iOS e Android',
    ],
  },
  {
    id: 'a4b',
    classId: '11',
    dia: 'quarta',
    dayOfWeek: 3,
    hora: '10:00',
    horaFim: '12:00',
    disciplina: 'Banco de Dados',
    subjectId: '2',
    professor: 'Maria Santos',
    teacherId: '1',
    sala: 'Sala 102',
    semester: '2024.1',
    resumo: 'Modelagem de dados e SQL. Normalização, consultas e integração com aplicações.',
    conteudo: [
      'Revisão de SQL',
      'Funções agregadas',
      'Window functions',
      'Case e coalesce',
      'Índices compostos',
      'Subqueries correlacionadas',
      'EXISTS e IN',
      'UNION e UNION ALL',
      'Temporary tables',
      'Cursors e loops',
      'Error handling em procedures',
      'Audit logging',
      'Data masking',
      'Compliance e LGPD',
    ],
  },
  {
    id: 'a4',
    classId: '3',
    dia: 'quarta',
    dayOfWeek: 3,
    hora: '14:00',
    horaFim: '16:00',
    disciplina: 'Desenvolvimento Web',
    subjectId: '3',
    professor: 'Maria Santos',
    teacherId: '1',
    sala: 'Sala 103',
    semester: '2024.1',
    resumo: 'Frameworks modernos. React, Vue e boas práticas de desenvolvimento.',
    conteudo: [
      'Introdução ao React',
      'Componentes funcionais',
      'Hooks e ciclo de vida',
      'Vue.js: composição e reatividade',
      'Comparativo React vs Vue',
      'Boas práticas e padrões',
      'Virtual DOM e reconciliação',
      'useMemo e useCallback',
      'Custom hooks',
      'Composition API (Vue 3)',
      'Pinia e Vuex',
      'Server components (React)',
      'Suspense e lazy loading',
      'Error boundaries',
      'Testing Library',
    ],
  },
  {
    id: 'a5',
    classId: '2',
    dia: 'quinta',
    dayOfWeek: 4,
    hora: '08:00',
    horaFim: '10:00',
    disciplina: 'Banco de Dados',
    subjectId: '2',
    professor: 'Maria Santos',
    teacherId: '1',
    sala: 'Sala 102',
    semester: '2024.1',
    resumo: 'NoSQL e bancos documentais. MongoDB e padrões de modelagem.',
    conteudo: [
      'Conceitos NoSQL',
      'MongoDB: documentos e coleções',
      'Operadores de consulta',
      'Agregação e pipeline',
      'Padrões de modelagem documental',
      'Índices e performance',
      'Replicação e sharding',
      'Documentos embutidos vs referências',
      'Operadores $match, $group, $lookup',
      'Text search e índices',
      'Change streams',
      'MongoDB Atlas e cloud',
      'Transações em documentos',
      'Schema validation',
      'Backup e restore',
    ],
  },
  {
    id: 'a5b',
    classId: '6',
    dia: 'quinta',
    dayOfWeek: 4,
    hora: '10:00',
    horaFim: '12:00',
    disciplina: 'Programação Mobile',
    subjectId: '1',
    professor: 'Maria Santos',
    teacherId: '1',
    sala: 'Sala 101',
    semester: '2024.1',
    resumo: 'APIs e estado global. Consumo de dados, Context API e persistência local.',
    conteudo: [
      'Consumo de APIs com fetch/axios',
      'Context API e providers',
      'useReducer e estado complexo',
      'AsyncStorage e persistência',
      'Tratamento de erros e loading',
      'Cache e otimização',
      'React Query / TanStack Query',
      'Retry e exponential backoff',
      'Offline-first strategies',
      'Redux Toolkit e slices',
      'Zustand para estado leve',
      'Persistência com MMKV',
      'Skeleton loaders',
      'Error boundaries por rota',
      'Analytics e tracking',
    ],
  },
  {
    id: 'a5c',
    classId: '7',
    dia: 'quinta',
    dayOfWeek: 4,
    hora: '14:00',
    horaFim: '16:00',
    disciplina: 'Desenvolvimento Web',
    subjectId: '3',
    professor: 'Maria Santos',
    teacherId: '1',
    sala: 'Sala 103',
    semester: '2024.1',
    resumo: 'Frameworks modernos. React, Vue e boas práticas de desenvolvimento.',
    conteudo: [
      'React: renderização condicional',
      'Listas e keys',
      'Formulários controlados',
      'Vue: diretivas e computed',
      'Testes unitários',
      'Controlled vs uncontrolled',
      'Form libraries (Formik, React Hook Form)',
      'Validação com Zod ou Yup',
      'Vue: v-if, v-for, v-model',
      'Computed e watchers',
      'Vitest e Jest',
      'Mocking e MSW',
      'E2E com Playwright',
      'CI/CD para frontend',
    ],
  },
  {
    id: 'a6a',
    classId: '8',
    dia: 'sexta',
    dayOfWeek: 5,
    hora: '08:00',
    horaFim: '10:00',
    disciplina: 'Programação Mobile',
    subjectId: '1',
    professor: 'Maria Santos',
    teacherId: '1',
    sala: 'Sala 101',
    semester: '2024.1',
    resumo: 'Introdução ao React Native e Expo. Estrutura de componentes, navegação e estilização.',
    conteudo: [
      'Revisão de componentes',
      'Estilização avançada',
      'SafeAreaView e status bar',
      'Modais e alertas',
      'Debug e DevTools',
      'Styled Components / NativeWind',
      'Theme provider e dark mode',
      'Bottom sheets e drawers',
      'Splash screen e loading',
      'Deep linking',
      'Biometria e segurança',
      'Crashlytics e Sentry',
      'A/B testing',
      'Feature flags',
    ],
  },
  {
    id: 'a6b',
    classId: '9',
    dia: 'sexta',
    dayOfWeek: 5,
    hora: '10:00',
    horaFim: '12:00',
    disciplina: 'Banco de Dados',
    subjectId: '2',
    professor: 'Maria Santos',
    teacherId: '1',
    sala: 'Sala 102',
    semester: '2024.1',
    resumo: 'Modelagem de dados e SQL. Normalização, consultas e integração com aplicações.',
    conteudo: [
      'Revisão geral de SQL',
      'Planejamento de banco',
      'Migrações e versionamento',
      'Documentação de schema',
      'Flyway e Liquibase',
      'Schema migrations em produção',
      'Rollback strategies',
      'Data dictionary',
      'ERD tools (dbdiagram.io)',
      'Versionamento de dados',
      'Blue-green deployments',
      'Monitoring e alertas',
      'Capacity planning',
    ],
  },
  {
    id: 'a6',
    classId: '3',
    dia: 'sexta',
    dayOfWeek: 5,
    hora: '14:00',
    horaFim: '16:00',
    disciplina: 'Desenvolvimento Web',
    subjectId: '3',
    professor: 'Maria Santos',
    teacherId: '1',
    sala: 'Sala 103',
    semester: '2024.1',
    resumo: 'Frameworks modernos. React, Vue e boas práticas de desenvolvimento.',
    conteudo: [
      'SPA e roteamento',
      'State management (Redux, Pinia)',
      'Server-side rendering',
      'Deploy e CI/CD',
      'React Router e Vue Router',
      'Lazy loading de rotas',
      'Guards e middleware',
      'Next.js e Nuxt',
      'Static generation vs SSR',
      'Vercel e Netlify',
      'Docker para frontend',
      'Lighthouse e Core Web Vitals',
      'Bundle analysis',
      'Tree shaking e code splitting',
    ],
  },
  {
    id: 'a7',
    classId: '12',
    dia: 'sábado',
    dayOfWeek: 6,
    hora: '09:00',
    horaFim: '11:00',
    disciplina: 'Programação Mobile',
    subjectId: '1',
    professor: 'Maria Santos',
    teacherId: '1',
    sala: 'Sala 101',
    semester: '2024.1',
    resumo: 'Workshop prático de desenvolvimento mobile.',
    conteudo: [
      'Projeto prático: app completo',
      'Integração com backend',
      'Autenticação e permissões',
      'Push notifications',
      'Testes em dispositivos reais',
      'Publicação nas lojas',
      'Métricas e analytics',
      'Arquitetura do projeto',
      'JWT e refresh tokens',
      'OAuth e social login',
      'Expo Notifications',
      'TestFlight e internal testing',
      'Store listing e screenshots',
      'ASO (App Store Optimization)',
      'Crash reports e feedback',
      'Atualizações OTA',
    ],
  },
  {
    id: 'a8',
    classId: '13',
    dia: 'domingo',
    dayOfWeek: 0,
    hora: '14:00',
    horaFim: '16:00',
    disciplina: 'Desenvolvimento Web',
    subjectId: '3',
    professor: 'Maria Santos',
    teacherId: '1',
    sala: 'Sala 103',
    semester: '2024.1',
    resumo: 'Aula especial de revisão.',
    conteudo: [
      'Revisão de HTML e CSS',
      'Revisão de JavaScript',
      'Revisão de frameworks',
      'Dúvidas e exercícios',
      'Preparação para avaliação',
      'Resumo de semântica e acessibilidade',
      'Resumo de flexbox e grid',
      'Resumo de hooks e estado',
      'Resumo de SQL e NoSQL',
      'Boas práticas de código',
      'Estrutura de projetos',
      'Documentação e comentários',
      'Git e workflow',
      'Apresentação do projeto final',
    ],
  },
];

// Aulas organizadas por dia da semana (para consulta rápida)
export const mockAulasPorDia = {
  segunda: mockAulas.filter((a) => a.dayOfWeek === 1),
  terca: mockAulas.filter((a) => a.dayOfWeek === 2),
  quarta: mockAulas.filter((a) => a.dayOfWeek === 3),
  quinta: mockAulas.filter((a) => a.dayOfWeek === 4),
  sexta: mockAulas.filter((a) => a.dayOfWeek === 5),
  sabado: mockAulas.filter((a) => a.dayOfWeek === 6),
  domingo: mockAulas.filter((a) => a.dayOfWeek === 0),
};

// Status das disciplinas por semestre: aprovado, reprovado, recuperação
export const mockDisciplinaStatus = [
  { subjectId: '1', semester: '2024.1', status: 'recuperacao' },
  { subjectId: '2', semester: '2024.1', status: 'aprovado' },
  { subjectId: '3', semester: '2024.1', status: 'reprovado' },
  { subjectId: '1', semester: '2023.2', status: 'aprovado' },
  { subjectId: '2', semester: '2023.2', status: 'reprovado' },
  { subjectId: '3', semester: '2023.2', status: 'aprovado' },
  { subjectId: '1', semester: '2024.2', status: 'aprovado' },
  { subjectId: '2', semester: '2024.2', status: 'aprovado' },
  { subjectId: '3', semester: '2024.2', status: 'aprovado' },
];

// Detalhes das disciplinas: resumo, comentários, notas, frequência
export const mockDisciplinaDetalhes = [
  {
    subjectId: '1',
    semester: '2024.1',
    resumo:
      'Programação Mobile aborda o desenvolvimento de aplicativos para dispositivos móveis utilizando React Native e Expo. O conteúdo inclui estrutura de componentes, navegação, estilização, hooks, integração com APIs, persistência local e publicação nas lojas. O aluno demonstrou boa evolução nos conceitos fundamentais, porém precisa reforçar a parte de gerenciamento de estado e testes.',
    comentarios: [
      { data: '2024-03-02', texto: 'Bom desempenho na entrega do projeto de componentes. Continue praticando a organização do código.' },
      { data: '2024-03-09', texto: 'A participação nas aulas práticas melhorou bastante. Parabéns pelo empenho!' },
      { data: '2024-03-16', texto: 'Atenção à documentação do código. Inclua comentários nas funções mais complexas.' },
      { data: '2024-03-23', texto: 'A prova prática apresentou dificuldades com o uso de Context API. Recomendo revisar o material.' },
      { data: '2024-03-30', texto: 'O trabalho em grupo foi bem executado. A integração com APIs está mais sólida.' },
      { data: '2024-04-06', texto: 'Frequência abaixo do esperado no último mês. Importante manter a presença para a recuperação.' },
      { data: '2024-04-13', texto: 'Bom progresso na revisão dos conceitos. Foco em useState e useEffect para a prova de recuperação.' },
    ],
    notas: [
      { avaliacao: 'Prova 1 - Teoria', valor: 6.5, peso: 2 },
      { avaliacao: 'Prova 2 - Prática', valor: 5.0, peso: 2 },
      { avaliacao: 'Trabalho em grupo', valor: 8.0, peso: 1 },
      { avaliacao: 'Atividades práticas', valor: 7.2, peso: 1 },
      { avaliacao: 'Prova de recuperação', valor: null, peso: 2 },
    ],
    frequencia: 78,
  },
  {
    subjectId: '2',
    semester: '2024.1',
    resumo:
      'Banco de Dados cobre modelagem de dados, SQL, normalização, joins, índices, transações e integração com aplicações. O aluno apresentou excelente desempenho ao longo do semestre, com domínio dos conceitos teóricos e práticos. As entregas foram pontuais e de boa qualidade.',
    comentarios: [
      { data: '2024-03-03', texto: 'Excelente trabalho no diagrama ER. A modelagem está correta e bem documentada.' },
      { data: '2024-03-10', texto: 'As consultas SQL estão bem estruturadas. Continue assim!' },
      { data: '2024-03-17', texto: 'Ótima apresentação do projeto de normalização. Conceitos bem aplicados.' },
      { data: '2024-03-24', texto: 'Prova teórica com nota acima da média. Parabéns!' },
      { data: '2024-03-31', texto: 'O projeto final demonstrou domínio completo dos tópicos. Excelente!' },
    ],
    notas: [
      { avaliacao: 'Prova 1 - Teoria', valor: 8.5, peso: 2 },
      { avaliacao: 'Prova 2 - Prática', valor: 9.0, peso: 2 },
      { avaliacao: 'Projeto de modelagem', valor: 9.5, peso: 1 },
      { avaliacao: 'Atividades em sala', valor: 8.8, peso: 1 },
    ],
    frequencia: 95,
  },
  {
    subjectId: '3',
    semester: '2024.1',
    resumo:
      'Desenvolvimento Web aborda HTML5, CSS3, JavaScript, frameworks modernos (React, Vue), responsividade e boas práticas. O aluno teve dificuldades com os conceitos de estado e ciclo de vida dos componentes. A frequência irregular impactou o acompanhamento do conteúdo. Recomenda-se cursar a disciplina novamente com maior dedicação.',
    comentarios: [
      { data: '2024-03-04', texto: 'Atenção à entrega dos exercícios. Alguns estavam incompletos.' },
      { data: '2024-03-11', texto: 'Faltas consecutivas prejudicaram o entendimento de flexbox e grid. Procure a monitoria.' },
      { data: '2024-03-18', texto: 'A prova prática mostrou dificuldades com JavaScript assíncrono. Revisar Promises e async/await.' },
      { data: '2024-03-25', texto: 'O trabalho em grupo foi entregue com atraso. Organize melhor os prazos.' },
      { data: '2024-04-01', texto: 'Frequência abaixo do mínimo. Importante manter 75% de presença.' },
      { data: '2024-04-08', texto: 'Resultado da prova final abaixo da média. Recomendo refazer a disciplina.' },
    ],
    notas: [
      { avaliacao: 'Prova 1 - Teoria', valor: 4.0, peso: 2 },
      { avaliacao: 'Prova 2 - Prática', valor: 3.5, peso: 2 },
      { avaliacao: 'Trabalho em grupo', valor: 6.0, peso: 1 },
      { avaliacao: 'Atividades práticas', valor: 5.0, peso: 1 },
    ],
    frequencia: 62,
  },
  // 2023.2
  {
    subjectId: '1',
    semester: '2023.2',
    resumo: 'Introdução à programação mobile com React Native. Conceitos básicos de componentes e navegação.',
    comentarios: [
      { data: '2023-10-02', texto: 'Bom início no curso. Continue praticando.' },
      { data: '2023-10-16', texto: 'Evolução positiva. Projeto bem estruturado.' },
    ],
    notas: [
      { avaliacao: 'Prova 1', valor: 7.5, peso: 2 },
      { avaliacao: 'Prova 2', valor: 8.0, peso: 2 },
      { avaliacao: 'Projeto final', valor: 8.5, peso: 1 },
    ],
    frequencia: 88,
  },
  {
    subjectId: '2',
    semester: '2023.2',
    resumo: 'Modelagem e SQL. O aluno teve dificuldades na prova final.',
    comentarios: [
      { data: '2023-10-03', texto: 'Bom desempenho nas atividades práticas.' },
      { data: '2023-10-24', texto: 'Atenção aos conceitos de normalização para a prova.' },
    ],
    notas: [
      { avaliacao: 'Prova 1', valor: 6.0, peso: 2 },
      { avaliacao: 'Prova 2', valor: 4.5, peso: 2 },
      { avaliacao: 'Projeto', valor: 7.0, peso: 1 },
    ],
    frequencia: 72,
  },
  {
    subjectId: '3',
    semester: '2023.2',
    resumo: 'HTML, CSS e JavaScript. Desempenho satisfatório.',
    comentarios: [
      { data: '2023-10-04', texto: 'Participação ativa nas aulas. Continue assim!' },
    ],
    notas: [
      { avaliacao: 'Prova 1', valor: 8.0, peso: 2 },
      { avaliacao: 'Prova 2', valor: 7.5, peso: 2 },
      { avaliacao: 'Projeto', valor: 8.0, peso: 1 },
    ],
    frequencia: 90,
  },
  // 2024.2
  {
    subjectId: '1',
    semester: '2024.2',
    resumo: 'Avançado em React Native. Estado global, testes e publicação.',
    comentarios: [
      { data: '2024-08-05', texto: 'Boa recuperação! Continue se dedicando.' },
    ],
    notas: [
      { avaliacao: 'Prova 1', valor: 8.5, peso: 2 },
      { avaliacao: 'Prova 2', valor: 7.8, peso: 2 },
      { avaliacao: 'Projeto', valor: 9.0, peso: 1 },
    ],
    frequencia: 92,
  },
  {
    subjectId: '2',
    semester: '2024.2',
    resumo: 'NoSQL e bancos documentais. Excelente desempenho.',
    comentarios: [
      { data: '2024-08-06', texto: 'Domínio dos conceitos de MongoDB. Parabéns!' },
    ],
    notas: [
      { avaliacao: 'Prova 1', valor: 9.0, peso: 2 },
      { avaliacao: 'Prova 2', valor: 9.2, peso: 2 },
      { avaliacao: 'Projeto', valor: 9.5, peso: 1 },
    ],
    frequencia: 98,
  },
  {
    subjectId: '3',
    semester: '2024.2',
    resumo: 'Frameworks modernos. React e Vue. Aprovado com boa nota.',
    comentarios: [
      { data: '2024-08-07', texto: 'Evolução significativa em relação ao semestre anterior.' },
    ],
    notas: [
      { avaliacao: 'Prova 1', valor: 7.5, peso: 2 },
      { avaliacao: 'Prova 2', valor: 8.0, peso: 2 },
      { avaliacao: 'Projeto', valor: 8.5, peso: 1 },
    ],
    frequencia: 85,
  },
];

// Presenças - mock para 2, 3, 4 e 5 de março de 2024
export const mockAttendance = [
  { id: '1', studentId: '1', classId: '1', date: '2024-03-05', status: 'present', timestamp: null, latitude: null, longitude: null },
  { id: '2', studentId: '1', classId: '2', date: '2024-03-04', status: 'absent', timestamp: null, latitude: null, longitude: null },
  { id: '3', studentId: '1', classId: '12', date: '2024-03-02', status: 'present', timestamp: null, latitude: null, longitude: null },
  { id: '4', studentId: '1', classId: '13', date: '2024-03-03', status: 'absent', timestamp: null, latitude: null, longitude: null },
  { id: '5', studentId: '1', classId: '1', date: '2024-03-04', status: 'present', timestamp: null, latitude: null, longitude: null },
  { id: '6', studentId: '1', classId: '4', date: '2024-03-04', status: 'absent', timestamp: null, latitude: null, longitude: null },
  { id: '7', studentId: '1', classId: '5', date: '2024-03-04', status: 'pending', timestamp: null, latitude: null, longitude: null },
  { id: '8', studentId: '1', classId: '2', date: '2024-03-05', status: 'absent', timestamp: null, latitude: null, longitude: null },
  { id: '9', studentId: '1', classId: '3', date: '2024-03-05', status: 'pending', timestamp: null, latitude: null, longitude: null },
  // 2023.2 - 6 presentes de 8 = 75%
  { id: '10', studentId: '1', classId: '20', date: '2023-10-02', status: 'present', timestamp: null, latitude: null, longitude: null },
  { id: '11', studentId: '1', classId: '21', date: '2023-10-03', status: 'present', timestamp: null, latitude: null, longitude: null },
  { id: '12', studentId: '1', classId: '22', date: '2023-10-04', status: 'absent', timestamp: null, latitude: null, longitude: null },
  { id: '13', studentId: '1', classId: '20', date: '2023-10-09', status: 'present', timestamp: null, latitude: null, longitude: null },
  { id: '14', studentId: '1', classId: '21', date: '2023-10-10', status: 'present', timestamp: null, latitude: null, longitude: null },
  { id: '15', studentId: '1', classId: '22', date: '2023-10-11', status: 'present', timestamp: null, latitude: null, longitude: null },
  { id: '16', studentId: '1', classId: '20', date: '2023-10-16', status: 'present', timestamp: null, latitude: null, longitude: null },
  { id: '17', studentId: '1', classId: '21', date: '2023-10-17', status: 'absent', timestamp: null, latitude: null, longitude: null },
  // 2024.2 - 9 presentes de 10 = 90%
  { id: '18', studentId: '1', classId: '30', date: '2024-08-05', status: 'present', timestamp: null, latitude: null, longitude: null },
  { id: '19', studentId: '1', classId: '31', date: '2024-08-06', status: 'present', timestamp: null, latitude: null, longitude: null },
  { id: '20', studentId: '1', classId: '32', date: '2024-08-07', status: 'present', timestamp: null, latitude: null, longitude: null },
  { id: '21', studentId: '1', classId: '30', date: '2024-08-12', status: 'present', timestamp: null, latitude: null, longitude: null },
  { id: '22', studentId: '1', classId: '31', date: '2024-08-13', status: 'absent', timestamp: null, latitude: null, longitude: null },
  { id: '23', studentId: '1', classId: '32', date: '2024-08-14', status: 'present', timestamp: null, latitude: null, longitude: null },
  { id: '24', studentId: '1', classId: '30', date: '2024-08-19', status: 'present', timestamp: null, latitude: null, longitude: null },
  { id: '25', studentId: '1', classId: '31', date: '2024-08-20', status: 'present', timestamp: null, latitude: null, longitude: null },
  { id: '26', studentId: '1', classId: '32', date: '2024-08-21', status: 'present', timestamp: null, latitude: null, longitude: null },
  { id: '27', studentId: '1', classId: '30', date: '2024-08-26', status: 'present', timestamp: null, latitude: null, longitude: null },
];

// Chamadas (Professor) - Histórico mockado por turma (teacherId 1 = Maria)
export const mockCalls = [
  // Turma 1 - Programação Mobile (teacher 1)
  { id: 'c1', classId: '1', teacherId: '1', startTime: '2024-03-11T08:00:00', endTime: '2024-03-11T10:00:00', status: 'ended', attendanceList: [] },
  { id: 'c2', classId: '1', teacherId: '1', startTime: '2024-03-04T08:00:00', endTime: '2024-03-04T10:00:00', status: 'ended', attendanceList: [] },
  { id: 'c3', classId: '1', teacherId: '1', startTime: '2024-02-26T08:00:00', endTime: '2024-02-26T10:00:00', status: 'ended', attendanceList: [] },
  { id: 'c4', classId: '1', teacherId: '1', startTime: '2024-02-19T08:00:00', endTime: '2024-02-19T10:00:00', status: 'ended', attendanceList: [] },
  { id: 'c5', classId: '1', teacherId: '1', startTime: '2024-02-12T08:00:00', endTime: '2024-02-12T10:00:00', status: 'ended', attendanceList: [] },
  // Turma 10 - Programação Mobile (teacher 1)
  { id: 'c6', classId: '10', teacherId: '1', startTime: '2024-03-13T08:00:00', endTime: '2024-03-13T10:00:00', status: 'ended', attendanceList: [] },
  { id: 'c7', classId: '10', teacherId: '1', startTime: '2024-03-06T08:00:00', endTime: '2024-03-06T10:00:00', status: 'ended', attendanceList: [] },
  { id: 'c8', classId: '10', teacherId: '1', startTime: '2024-02-28T08:00:00', endTime: '2024-02-28T10:00:00', status: 'ended', attendanceList: [] },
  // Turma 6 - Programação Mobile (teacher 1)
  { id: 'c9', classId: '6', teacherId: '1', startTime: '2024-03-14T10:00:00', endTime: '2024-03-14T12:00:00', status: 'ended', attendanceList: [] },
  { id: 'c10', classId: '6', teacherId: '1', startTime: '2024-03-07T10:00:00', endTime: '2024-03-07T12:00:00', status: 'ended', attendanceList: [] },
  // Turma 2 - Banco de Dados
  { id: 'c11', classId: '2', teacherId: '1', startTime: '2024-03-12T10:00:00', endTime: '2024-03-12T12:00:00', status: 'ended', attendanceList: [] },
  // Turma 3 - Desenvolvimento Web
  { id: 'c12', classId: '3', teacherId: '1', startTime: '2024-03-13T14:00:00', endTime: '2024-03-13T16:00:00', status: 'ended', attendanceList: [] },
  // Turma 40 - Gestão de Pessoas (Administração)
  { id: 'c13', classId: '40', teacherId: '1', startTime: '2024-03-11T08:00:00', endTime: '2024-03-11T10:00:00', status: 'ended', attendanceList: [] },
  // Turma 41 - Contabilidade e Finanças (Administração)
  { id: 'c14', classId: '41', teacherId: '1', startTime: '2024-03-12T10:00:00', endTime: '2024-03-12T12:00:00', status: 'ended', attendanceList: [] },
  // Turma 42 - Redes de Computadores
  { id: 'c15', classId: '42', teacherId: '1', startTime: '2024-03-11T14:00:00', endTime: '2024-03-11T16:00:00', status: 'ended', attendanceList: [] },
  // Turma 43 - Fundamentos de Enfermagem
  { id: 'c16', classId: '43', teacherId: '1', startTime: '2024-03-12T08:00:00', endTime: '2024-03-12T12:00:00', status: 'ended', attendanceList: [] },
  // Turma 44 - Gestão de Estoques (Logística)
  { id: 'c17', classId: '44', teacherId: '1', startTime: '2024-03-13T14:00:00', endTime: '2024-03-13T16:00:00', status: 'ended', attendanceList: [] },
];

// Pagamentos
export const mockPayments = [
  {
    id: '1',
    studentId: '1',
    description: 'Mensalidade Março 2024',
    amount: 450.0,
    dueDate: '2024-03-10',
    status: 'pending',
    competencia: '03/2024',
    barcode: '12345678901234567890123456789012345678901234',
    linhaDigitavel: '12345.67890 12345.678901 23456.789012 3 45678901234567',
  },
  {
    id: '2',
    studentId: '1',
    description: 'Mensalidade Fevereiro 2024',
    amount: 450.0,
    dueDate: '2024-02-10',
    status: 'paid',
    competencia: '02/2024',
    paidAt: '2024-02-08',
    barcode: '12345678901234567890123456789012345678901234',
    linhaDigitavel: '12345.67890 12345.678901 23456.789012 3 45678901234567',
  },
  {
    id: '3',
    studentId: '1',
    description: 'Mensalidade Abril 2024',
    amount: 450.0,
    dueDate: '2024-04-10',
    status: 'pending',
    competencia: '04/2024',
    barcode: '98765432109876543210987654321098765432109876',
    linhaDigitavel: '98765.43210 98765.432109 87654.321098 7 65432109876543',
  },
];

// Documentos
export const mockDocuments = [
  { id: '1', type: 'diploma', name: 'Diploma de Conclusão', url: null, studentId: '1' },
  { id: '2', type: 'certificate', name: 'Certificado de Curso', url: null, studentId: '1' },
  { id: '3', type: 'report', name: 'Boletim 2024.1', url: null, studentId: '1' },
];

// Notificações (userId '1' = aluno, '2' = professor)
export const mockNotifications = [
  {
    id: '1',
    userId: '1',
    title: 'Nova aula disponível',
    message: 'Aula de Programação Mobile às 08:00',
    read: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    userId: '1',
    title: 'Presença registrada',
    message: 'Sua presença na aula de Banco de Dados foi confirmada.',
    read: true,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: '3',
    userId: '2',
    title: 'Chamada iniciada',
    message: 'A turma de Programação Mobile está aguardando a chamada.',
    read: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: '4',
    userId: '2',
    title: 'Nova turma atribuída',
    message: 'Você foi designado para a turma de Desenvolvimento Web - 2024.1',
    read: true,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
];

export const initializeMockData = async () => {
  await database.setItem(KEYS.USERS, mockUsers);
  await database.setItem(KEYS.STUDENTS, mockStudents);
  await database.setItem(KEYS.TEACHERS, mockTeachers);
  await database.setItem(KEYS.COURSES, mockCourses);
  await database.setItem(KEYS.SUBJECTS, mockSubjects);
  await database.setItem(KEYS.CLASSES, mockClasses);
  await database.setItem(KEYS.AULAS, mockAulas);
  await database.setItem(KEYS.ATTENDANCE, mockAttendance);
  await database.setItem(KEYS.DISCIPLINA_STATUS, mockDisciplinaStatus);
  await database.setItem(KEYS.DISCIPLINA_DETALHES, mockDisciplinaDetalhes);
  await database.setItem(KEYS.CALLS, mockCalls);
  await database.setItem(KEYS.PAYMENTS, mockPayments);
  await database.setItem(KEYS.DOCUMENTS, mockDocuments);
  await database.setItem(KEYS.NOTIFICATIONS, mockNotifications);
};
